### ISSUE TITLE
Embedded Vimeo player cannot play even if prompted to

### ISSUE THREAD

**Issue by Cwpute** [abdullahezzat1/video-and-audio-blocker#2]
I was trying to access a video on this page: https://edu.ge.ch/site/archiprod/1988-d9045-contes-et-conteurs-5/
The embedded Vimeo player didn't start by itself, as expected, but it wouldn't succeed to play when i specifically asked it to. The video endlessly loads. I can freely watch the video if i disable the extension.

I understood this extension was to prevent video/audio from automatically playing, but does it completely shuts off any audio/video from playing entirely ?

**Comment by abdullahezzat1** [comment]
This extension is not just to prevent autoplay, but to prevent downloading the video/audio entirely!

**Comment by Cwpute** [comment]
understood 👍 i downloaded it to prevent pop-up videos from appearing but i didn't expect it would block all videos altogether. i thought embedded ones could at least be played if requested to do it
